"""SatQuery AI — Hallucination Control & Evidence Consistency Guard.

Validates model claims against radiometric evidence, spectral indices (NDVI/NDWI),
spatial bounding regions, and change detection delta statistics to suppress hallucinations
and flag unverified remote-sensing assertions.
"""

from dataclasses import dataclass, field
import re
from typing import Any, Dict, List, Optional
import numpy as np
from PIL import Image

from app.models.base import ConfidenceLevel, TaskType
from app.services.confidence_calibration import CalibratedConfidence, ConfidenceCalibrator
from app.utils.logging import get_logger

logger = get_logger("services.hallucination_guard")


@dataclass
class GuardAuditResult:
    """Audit findings generated by the Hallucination Control Layer."""
    is_consistent: bool
    consistency_score: float  # 0.0 to 1.0
    detected_claims: List[str] = field(default_factory=list)
    violations: List[str] = field(default_factory=list)
    advisory_warning: Optional[str] = None
    calibrated_confidence: Optional[CalibratedConfidence] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_consistent": self.is_consistent,
            "consistency_score": round(self.consistency_score, 3),
            "detected_claims": self.detected_claims,
            "violations": self.violations,
            "advisory_warning": self.advisory_warning,
            "calibrated_confidence": (
                self.calibrated_confidence.to_dict()
                if self.calibrated_confidence
                else None
            ),
        }


class EvidenceConsistencyValidator:
    """Verifies that natural-language assertions are backed by pixel-level radiometric evidence."""

    @classmethod
    def extract_scene_spectral_stats(cls, image: Image.Image) -> Dict[str, float]:
        """Compute average RGB bands and surrogate spectral indices from preview image."""
        arr = np.array(image.convert("RGB"), dtype=np.float32)
        r = arr[:, :, 0]
        g = arr[:, :, 1]
        b = arr[:, :, 2]

        # Normalized Green-Red Difference Index (surrogate NDVI)
        gr_sum = g + r + 1e-6
        grdi = float(np.mean((g - r) / gr_sum))

        # Normalized Green-Blue Difference Index (surrogate NDWI)
        gb_sum = g + b + 1e-6
        gbdi = float(np.mean((g - b) / gb_sum))

        # Mean brightness
        brightness = float(np.mean(arr))

        return {
            "mean_grdi": grdi,
            "mean_gbdi": gbdi,
            "mean_brightness": brightness,
            "red_mean": float(np.mean(r)),
            "green_mean": float(np.mean(g)),
            "blue_mean": float(np.mean(b)),
        }

    @classmethod
    def validate_assertion(
        cls,
        answer_text: str,
        task: TaskType,
        images: List[Image.Image],
        evidence_dict: Optional[Dict[str, Any]] = None,
    ) -> GuardAuditResult:
        """Audit the textual answer against spectral rasters and evidence records."""
        ans = answer_text.lower()
        claims: List[str] = []
        violations: List[str] = []
        consistency_score = 1.0

        stats = (
            cls.extract_scene_spectral_stats(images[0])
            if images and len(images) > 0
            else {}
        )

        # 1. Audit Vegetation Claims
        veg_keywords = ["vegetation", "forest", "tree", "canopy", "dense green", "crop"]
        if any(w in ans for w in veg_keywords):
            claims.append("Vegetation / Canopy Presence")
            grdi = stats.get("mean_grdi", 0.0)
            green_dom = stats.get("green_mean", 0.0) > stats.get("red_mean", 0.0)
            if grdi < -0.15 and not green_dom:
                violations.append(
                    f"Vegetation claimed, but spectral GRDI ({round(grdi, 3)}) indicates negligible photosynthetic green reflectance."
                )
                consistency_score -= 0.35

        # 2. Audit Water Body Claims
        water_keywords = ["water body", "reservoir", "river", "lake", "ocean", "inundat"]
        if any(w in ans for w in water_keywords):
            claims.append("Surface Water / Hydrological Feature")
            blue_dom = stats.get("blue_mean", 0.0) >= stats.get("red_mean", 0.0)
            brightness = stats.get("mean_brightness", 100.0)
            # Water bodies typically have low red reflectance or dominant blue/green
            if stats.get("red_mean", 0.0) > 180 and not blue_dom:
                violations.append(
                    "Open water claimed, but high red radiance / spectral reflectance contradicts water absorption profile."
                )
                consistency_score -= 0.35

        # 3. Audit Temporal Change Claims
        if task in (TaskType.CHANGE_DETECTION, TaskType.CHANGE_VQA):
            change_stats = {}
            if evidence_dict and "change_detection_map" in evidence_dict:
                change_stats = evidence_dict["change_detection_map"].get("statistics", {})

            changed_pct = change_stats.get("changed_percentage", None)
            if changed_pct is not None:
                claims.append(f"Quantified Change ({round(changed_pct, 1)}%)")
                if "significant change" in ans or "major change" in ans or "widespread" in ans:
                    if changed_pct < 1.0:
                        violations.append(
                            f"Major change claimed in text, but measured bi-temporal delta is only {round(changed_pct, 2)}%."
                        )
                        consistency_score -= 0.40
                elif "no significant change" in ans or "negligible" in ans or "identical" in ans:
                    if changed_pct > 20.0:
                        violations.append(
                            f"No change claimed in text, but measured bi-temporal delta shows {round(changed_pct, 2)}% changed pixels."
                        )
                        consistency_score -= 0.45

        # 4. Audit Grounding Bounding Box Claims
        if task == TaskType.GROUNDING and evidence_dict:
            grounding_data = evidence_dict.get("grounding_overlay", {})
            bboxes = grounding_data.get("bounding_boxes", [])
            claims.append(f"Localized Bounding Boxes ({len(bboxes)})")
            if "located" in ans and len(bboxes) == 0:
                violations.append(
                    "Answer claims features were localized, but zero valid bounding boxes were detected."
                )
                consistency_score -= 0.40

        consistency_score = max(0.1, min(1.0, consistency_score))
        is_consistent = len(violations) == 0

        advisory_warning = None
        if not is_consistent:
            advisory_warning = (
                "⚠️ Hallucination Advisory: " + " ".join(violations)
            )

        return GuardAuditResult(
            is_consistent=is_consistent,
            consistency_score=consistency_score,
            detected_claims=claims,
            violations=violations,
            advisory_warning=advisory_warning,
        )


class HallucinationGuard:
    """Complete Hallucination Control Layer intercepting and auditing inference pipeline outputs."""

    @classmethod
    def audit_and_calibrate(
        cls,
        raw_answer: str,
        raw_confidence: float,
        task: TaskType,
        images: List[Image.Image],
        evidence_dict: Optional[Dict[str, Any]] = None,
    ) -> GuardAuditResult:
        """Run full cross-modal verification, consistency check, and confidence calibration."""
        # 1. Audit text against spectral rasters & evidence
        audit = EvidenceConsistencyValidator.validate_assertion(
            answer_text=raw_answer,
            task=task,
            images=images,
            evidence_dict=evidence_dict,
        )

        # 2. Calibrate confidence score with consistency scaling
        calibrated = ConfidenceCalibrator.calibrate(
            raw_confidence=raw_confidence,
            images=images,
            consistency_score=audit.consistency_score,
        )

        audit.calibrated_confidence = calibrated

        if not audit.is_consistent:
            logger.warning(
                "hallucination_guard_violation_flagged",
                task=task.value,
                violations=audit.violations,
                calibrated_confidence=calibrated.score,
            )

        return audit
